name: coin_master
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  #Firebase
  firebase_analytics: ^10.3.0
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.9.2

  #google
  google_sign_in: ^6.1.2
  shared_preferences: ^2.1.1
  internet_connection_checker_plus: ^2.2.0
  flutter_bloc: ^8.1.2
  logger: ^2.0.1
  equatable: ^2.0.5
  get_it: ^7.6.0
  built_value: ^8.6.2
  email_validator: ^2.1.17
  go_router:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  built_value_generator: ^8.6.2
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true
  assets:
    - assets/string_translations/
    - assets/images/

