// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUyRknubnkwtRkbsibkEIEDKtzhTFgipM',
    appId: '1:818648632114:web:8f011d480ce75a0b34652b',
    messagingSenderId: '818648632114',
    projectId: 'coin-master-2f2e8',
    authDomain: 'coin-master-2f2e8.firebaseapp.com',
    storageBucket: 'coin-master-2f2e8.appspot.com',
    measurementId: 'G-B0DQTNEJK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-N3Magt5MCIVNpfv3obA6cDZikIOpKc4',
    appId: '1:818648632114:android:aa4ee7525a533a8d34652b',
    messagingSenderId: '818648632114',
    projectId: 'coin-master-2f2e8',
    storageBucket: 'coin-master-2f2e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeVYQNcZs_dMmuubCmklTYHWn33aJlUVo',
    appId: '1:818648632114:ios:812777e3fcc1128734652b',
    messagingSenderId: '818648632114',
    projectId: 'coin-master-2f2e8',
    storageBucket: 'coin-master-2f2e8.appspot.com',
    androidClientId: '818648632114-mesp93fp5ucggn59u5ib867k48fr1skg.apps.googleusercontent.com',
    iosClientId: '818648632114-u4am30tobandh2jddaretuamnr8bs0og.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeVYQNcZs_dMmuubCmklTYHWn33aJlUVo',
    appId: '1:818648632114:ios:812777e3fcc1128734652b',
    messagingSenderId: '818648632114',
    projectId: 'coin-master-2f2e8',
    storageBucket: 'coin-master-2f2e8.appspot.com',
    androidClientId: '818648632114-mesp93fp5ucggn59u5ib867k48fr1skg.apps.googleusercontent.com',
    iosClientId: '818648632114-u4am30tobandh2jddaretuamnr8bs0og.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinMaster',
  );
}
